name: dart_frog_project
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

# for a real project we wouldn't have the aws_lambda_dart_runtime, shelf, and shelf_router dependencies here, as users wouldn't have this code
dependencies:
  dart_frog: ^0.3.0
  aws_lambda_dart_runtime: "^1.1.0"
  shelf: ^1.1.0
  shelf_router: ^1.0.0
dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
