name: dart_cakework
description: A sample Dart application
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # package_config: "^2.1.0"
  yaml: "^3.1.1"
#   path: ^1.8.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  dart_frog: ^0.3.0
  aws_lambda_dart_runtime: "^1.1.0"
    # git: https://github.com/awslabs/aws-lambda-dart-runtime.git
    

dev_dependencies:
  build_runner:
# dev_dependencies:
  # lints: ^2.0.0
  # test: ^1.21.0
